<<<<<<< HEAD
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'
=======
# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest
>>>>>>> 30e1205540984e58fe54d33a739f75ce9a9a3462

steps:
- task: NodeTool@0
  inputs:
<<<<<<< HEAD
    versionSpec: '14.x' # Use the Node.js version appropriate for your project
  displayName: 'Install Node.js'

- script: |
    echo "Starting npm install..."
    npm install
    echo "Finished npm install."
    echo "Starting npm run build..."
    npm run build
    echo "Finished npm run build."
  displayName: 'Install dependencies and build'
  continueOnError: false

- task: CopyFiles@2
  inputs:
    SourceFolder: 'build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/webapp'
  displayName: 'Copy files to staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/webapp'
    artifactName: 'webapp'
  displayName: 'Publish build artifacts'

- task: AzureStaticWebApp@0
  inputs:
    azure_static_web_apps_api_token: $(AzureStaticWebAppApiToken) # Add this token as a secret in your pipeline
    app_location: '/' # Root of the React app
    output_location: 'build' # Location of the build output
  displayName: 'Deploy to Azure Static Web Apps'
=======
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
>>>>>>> 30e1205540984e58fe54d33a739f75ce9a9a3462
